[github]
Manager = "Manager-io/Manager"
Kitapp = "johnlindquist/kitapp"
balenaEtcher = "balena-io/etcher"
acreom = "Acreom/releases"

[webpage]
Mendeley = "https://www.mendeley.com/download-reference-manager/macOS"

[direct]
RemNote = "https://backend.remnote.com/desktop/mac"
